// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clicks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertClick = `-- name: InsertClick :one
INSERT INTO clicks (url_id, ip_address, clicked_at, user_agent, referer, device_type, country)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, url_id, clicked_at, ip_address, user_agent, referer, device_type, country
`

type InsertClickParams struct {
	UrlID      pgtype.Int8      `json:"urlId"`
	IpAddress  pgtype.Text      `json:"ipAddress"`
	ClickedAt  pgtype.Timestamp `json:"clickedAt"`
	UserAgent  pgtype.Text      `json:"userAgent"`
	Referer    pgtype.Text      `json:"referer"`
	DeviceType pgtype.Text      `json:"deviceType"`
	Country    pgtype.Text      `json:"country"`
}

func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) (Click, error) {
	row := q.db.QueryRow(ctx, insertClick,
		arg.UrlID,
		arg.IpAddress,
		arg.ClickedAt,
		arg.UserAgent,
		arg.Referer,
		arg.DeviceType,
		arg.Country,
	)
	var i Click
	err := row.Scan(
		&i.ID,
		&i.UrlID,
		&i.ClickedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Referer,
		&i.DeviceType,
		&i.Country,
	)
	return i, err
}
