// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Click struct {
	ID         int64            `json:"id"`
	UrlID      pgtype.Int8      `json:"urlId"`
	ClickedAt  pgtype.Timestamp `json:"clickedAt"`
	IpAddress  pgtype.Text      `json:"ipAddress"`
	UserAgent  pgtype.Text      `json:"userAgent"`
	Referer    pgtype.Text      `json:"referer"`
	DeviceType pgtype.Text      `json:"deviceType"`
	Country    pgtype.Text      `json:"country"`
}

type Url struct {
	ID          int64            `json:"id"`
	ShortCode   string           `json:"shortCode"`
	OriginalUrl string           `json:"originalUrl"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
	UpdatedAt   pgtype.Timestamp `json:"updatedAt"`
	ExpiresAt   pgtype.Timestamp `json:"expiresAt"`
	ClickCount  pgtype.Int8      `json:"clickCount"`
	IsActive    pgtype.Bool      `json:"isActive"`
}
