// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CheckShortCodeExists(ctx context.Context, shortCode string) (bool, error)
	// db/queries/urls.sql
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeactivateURL(ctx context.Context, shortCode string) error
	GetURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	GetURLStats(ctx context.Context, shortCode string) (GetURLStatsRow, error)
	IncrementClickCount(ctx context.Context, shortCode string) error
	InsertClick(ctx context.Context, arg InsertClickParams) (Click, error)
	ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error)
}

var _ Querier = (*Queries)(nil)
