// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckShortCodeExists(ctx context.Context, shortCode string) (bool, error)
	CountAllClicks(ctx context.Context) (int64, error)
	CountClicksByURLID(ctx context.Context, urlID pgtype.Int8) (int64, error)
	CountClicksToday(ctx context.Context) (int64, error)
	CountURLs(ctx context.Context) (int64, error)
	CountURLsToday(ctx context.Context) (int64, error)
	// db/queries/urls.sql
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	DeactivateURL(ctx context.Context, shortCode string) error
	GetClicksByURLID(ctx context.Context, arg GetClicksByURLIDParams) ([]Click, error)
	GetTopURLs(ctx context.Context, limit int32) ([]GetTopURLsRow, error)
	GetURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	GetURLStats(ctx context.Context, shortCode string) (GetURLStatsRow, error)
	IncrementClickCount(ctx context.Context, shortCode string) error
	InsertClick(ctx context.Context, arg InsertClickParams) (Click, error)
	ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error)
}

var _ Querier = (*Queries)(nil)
