// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllClicks = `-- name: CountAllClicks :one
SELECT COUNT(*) FROM clicks
`

func (q *Queries) CountAllClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllClicks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClicksToday = `-- name: CountClicksToday :one
SELECT COUNT(*) FROM clicks
WHERE DATE(clicked_at) = CURRENT_DATE
`

func (q *Queries) CountClicksToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countClicksToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countURLsToday = `-- name: CountURLsToday :one
SELECT COUNT(*) FROM urls
WHERE DATE(created_at) = CURRENT_DATE
`

func (q *Queries) CountURLsToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countURLsToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTopURLs = `-- name: GetTopURLs :many
SELECT 
    u.short_code,
    u.original_url,
    u.click_count
FROM urls u
ORDER BY u.click_count DESC
LIMIT $1
`

type GetTopURLsRow struct {
	ShortCode   string      `json:"shortCode"`
	OriginalUrl string      `json:"originalUrl"`
	ClickCount  pgtype.Int8 `json:"clickCount"`
}

func (q *Queries) GetTopURLs(ctx context.Context, limit int32) ([]GetTopURLsRow, error) {
	rows, err := q.db.Query(ctx, getTopURLs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopURLsRow{}
	for rows.Next() {
		var i GetTopURLsRow
		if err := rows.Scan(&i.ShortCode, &i.OriginalUrl, &i.ClickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
