// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkShortCodeExists = `-- name: CheckShortCodeExists :one
SELECT EXISTS(
    SELECT 1 FROM urls WHERE short_code = $1
) AS exists
`

func (q *Queries) CheckShortCodeExists(ctx context.Context, shortCode string) (bool, error) {
	row := q.db.QueryRow(ctx, checkShortCodeExists, shortCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createURL = `-- name: CreateURL :one

INSERT INTO urls (short_code, original_url)
VALUES ($1, $2)
RETURNING id, short_code, original_url, created_at, updated_at, expires_at, click_count, is_active
`

type CreateURLParams struct {
	ShortCode   string `json:"shortCode"`
	OriginalUrl string `json:"originalUrl"`
}

// db/queries/urls.sql
func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.IsActive,
	)
	return i, err
}

const deactivateURL = `-- name: DeactivateURL :exec
UPDATE urls
SET is_active = false
WHERE short_code = $1
`

func (q *Queries) DeactivateURL(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, deactivateURL, shortCode)
	return err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, original_url, created_at, updated_at, expires_at, click_count, is_active FROM urls
WHERE short_code = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.IsActive,
	)
	return i, err
}

const getURLStats = `-- name: GetURLStats :one
SELECT 
    short_code,
    original_url,
    click_count,
    created_at
FROM urls
WHERE short_code = $1 AND is_active = true
LIMIT 1
`

type GetURLStatsRow struct {
	ShortCode   string           `json:"shortCode"`
	OriginalUrl string           `json:"originalUrl"`
	ClickCount  pgtype.Int8      `json:"clickCount"`
	CreatedAt   pgtype.Timestamp `json:"createdAt"`
}

func (q *Queries) GetURLStats(ctx context.Context, shortCode string) (GetURLStatsRow, error) {
	row := q.db.QueryRow(ctx, getURLStats, shortCode)
	var i GetURLStatsRow
	err := row.Scan(
		&i.ShortCode,
		&i.OriginalUrl,
		&i.ClickCount,
		&i.CreatedAt,
	)
	return i, err
}

const incrementClickCount = `-- name: IncrementClickCount :exec
UPDATE urls
SET click_count = click_count + 1
WHERE short_code = $1
`

func (q *Queries) IncrementClickCount(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, incrementClickCount, shortCode)
	return err
}

const listURLs = `-- name: ListURLs :many
SELECT id, short_code, original_url, created_at, updated_at, expires_at, click_count, is_active FROM urls
WHERE is_active = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListURLsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListURLs(ctx context.Context, arg ListURLsParams) ([]Url, error) {
	rows, err := q.db.Query(ctx, listURLs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Url{}
	for rows.Next() {
		var i Url
		if err := rows.Scan(
			&i.ID,
			&i.ShortCode,
			&i.OriginalUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.ClickCount,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
